stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: |-
        num=`sed -n -e "/<mirrors>/=" $MAVEN_HOME/conf/settings.xml`
         sed -i "${num}a <mirror>" $MAVEN_HOME/conf/settings.xml
        sed -i "`expr $num + 1`a <id>localmaven</id>" $MAVEN_HOME/conf/settings.xml
        sed -i "`expr $num + 2`a <mirrorOf>*</mirrorOf>" $MAVEN_HOME/conf/settings.xml
        sed -i "`expr $num + 3`a <name>Nexus</name>" $MAVEN_HOME/conf/settings.xml
        sed -i "`expr $num + 4`a <url>https://nexus-devops.dfcv.com.cn/repository/maven-public/</url>" $MAVEN_HOME/conf/settings.xml
        sed -i "`expr $num + 5`a </mirror>" $MAVEN_HOME/conf/settings.xml
        mvn clean install -X
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nexus-demo/example-greenhouse:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry-devops.dfcv.com.cn
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}
